feat 自定义规则 && 优先级规则组 整体导入导出
jxxghp/MoviePilot-Frontend pull request #218
Opened 2024-10-28 04:36 UTC by thsrite

2024-10-28 05:41 UTC, jxxghp requested changes

2024-10-28 05:41 UTC, jxxghp commented on src/views/setting/AccountSettingRule.vue
> +  {title: '资源优先级', value: 'torrent'},
缩进、空格等格式变化请处理一下

2024-10-28 06:00 UTC, thsrite commented on src/views/setting/AccountSettingRule.vue
> +  {title: '资源优先级', value: 'torrent'},
> 缩进、空格等格式变化请处理一下

haole

2024-10-29 00:01 UTC, thsrite commented
@thsrite 老大，有空再看下

2024-10-29 00:01 UTC, merged