资源搜索支持指定站点
jxxghp/MoviePilot-Frontend pull request #244
Opened 2024-11-22 08:57 UTC by LongShengWen

根据个人日常用户发现的痛点增加的功能点，望采纳

2024-11-22 08:58 UTC, jxxghp commented
支持多选是不是更好？

2024-11-22 08:59 UTC, LongShengWen commented
哈哈，那先打回，我改一下

2024-11-22 09:02 UTC, jxxghp requested changes

2024-11-22 09:02 UTC, jxxghp commented on src/views/discover/MediaDetailView.vue
> +          <VSelect
建议支持多选

2024-11-22 09:55 UTC, LongShengWen commented on src/views/discover/MediaDetailView.vue
> +          <VSelect
已修改，完成测试

2025-02-07 15:10 UTC, JhouXerox commented
作者你好， 左上角全局搜索时是否也能增加指定站点

2025-02-08 01:28 UTC, JhouXerox commented
作者,我理解这个是在剧集详情里点搜索后可以选择站点.
是否考虑左上角全局搜索也加一个类似的

2025-02-20 05:24 UTC, closed without merging